auto: true

name: amaslenn.github.com
description: Blog of amaslenn
url: http://amaslenn.github.io

safe: false

# analytics
analytics:
  provider: google
  google:
    tracking_id: 'UA-37715886-1'

# comments
comments:
  provider: disqus
  disqus:
    short_name: amaslenn